// Generated by scripts/assemble-companion-rigs-v2.py. Review-only; never auto-register.
import type { CompanionRig } from './companionRig.js';
export const candidateRigs: Partial<Record<CompanionRig['species'], CompanionRig>> = {
  "bunny": {
    "version": 1,
    "species": "bunny",
    "formId": "base",
    "archetype": "upright",
    "canvas": [
      512,
      512
    ],
    "anchor": [
      256,
      448
    ],
    "safeBounds": [
      24,
      24,
      464,
      456
    ],
    "shadow": "runtime",
    "sleepExpression": "eyelids",
    "parts": [
      {
        "id": "ear_r",
        "source": "/assets/companions/rig-v2/bunny/base/ear_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          188.35,
          174.11
        ],
        "order": 0,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.12,
        "motion": "ear"
      },
      {
        "id": "ear_l",
        "source": "/assets/companions/rig-v2/bunny/base/ear_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          311.75,
          174.0
        ],
        "order": 1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -1,
        "phase": -0.18,
        "motion": "ear"
      },
      {
        "id": "tail",
        "source": "/assets/companions/rig-v2/bunny/base/tail.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          172.77,
          404.0
        ],
        "order": 2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "tail"
      },
      {
        "id": "foot_r",
        "source": "/assets/companions/rig-v2/bunny/base/foot_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          204.52,
          390.4
        ],
        "order": 3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "foot_l",
        "source": "/assets/companions/rig-v2/bunny/base/foot_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          306.03,
          401.2
        ],
        "order": 4,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.225,
        "motion": "leg"
      },
      {
        "id": "body",
        "source": "/assets/companions/rig-v2/bunny/base/body.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          253.01,
          368.0
        ],
        "order": 5,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "body"
      },
      {
        "id": "arm_r",
        "source": "/assets/companions/rig-v2/bunny/base/arm_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          193.0,
          301.99
        ],
        "order": 6,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.35,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "arm_l",
        "source": "/assets/companions/rig-v2/bunny/base/arm_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          327.0,
          302.0
        ],
        "order": 7,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -0.35,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "chest_fluff",
        "source": "/assets/companions/rig-v2/bunny/base/chest_fluff.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          257.97,
          278.35
        ],
        "order": 8,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      },
      {
        "id": "head",
        "source": "/assets/companions/rig-v2/bunny/base/head.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          257.0,
          275.0
        ],
        "order": 9,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "body",
        "stateSources": {
          "sleep": "/assets/companions/rig-v2/bunny/base/head_sleep.png"
        }
      }
    ]
  },
  "cat": {
    "version": 1,
    "species": "cat",
    "formId": "base",
    "archetype": "quadruped",
    "canvas": [
      512,
      512
    ],
    "anchor": [
      256,
      448
    ],
    "safeBounds": [
      24,
      24,
      464,
      456
    ],
    "shadow": "runtime",
    "sleepExpression": "eyelids",
    "parts": [
      {
        "id": "tail",
        "source": "/assets/companions/rig-v2/cat/base/tail.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          384.5,
          183.0
        ],
        "order": 0,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "tail"
      },
      {
        "id": "hind_leg_r",
        "source": "/assets/companions/rig-v2/cat/base/hind_leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          205.0,
          359.9
        ],
        "order": 1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.325,
        "motion": "leg"
      },
      {
        "id": "hind_leg_l",
        "source": "/assets/companions/rig-v2/cat/base/hind_leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          300.5,
          353.67
        ],
        "order": 2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "body",
        "source": "/assets/companions/rig-v2/cat/base/body.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          232.0,
          262.0
        ],
        "order": 3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "body"
      },
      {
        "id": "front_leg_r",
        "source": "/assets/companions/rig-v2/cat/base/front_leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          155.5,
          352.97
        ],
        "order": 4,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "front_leg_l",
        "source": "/assets/companions/rig-v2/cat/base/front_leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          212.0,
          344.0
        ],
        "order": 5,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.325,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "chest_fluff",
        "source": "/assets/companions/rig-v2/cat/base/chest_fluff.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          157.5,
          298.9
        ],
        "order": 6,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      },
      {
        "id": "head",
        "source": "/assets/companions/rig-v2/cat/base/head.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          175.0,
          110.75
        ],
        "order": 7,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "body",
        "stateSources": {
          "sleep": "/assets/companions/rig-v2/cat/base/head_sleep.png"
        }
      }
    ]
  },
  "child": {
    "version": 1,
    "species": "child",
    "formId": "base",
    "archetype": "upright",
    "canvas": [
      512,
      512
    ],
    "anchor": [
      256,
      448
    ],
    "safeBounds": [
      24,
      24,
      464,
      456
    ],
    "shadow": "runtime",
    "sleepExpression": "eyelids",
    "parts": [
      {
        "id": "tail",
        "source": "/assets/companions/rig-v2/child/base/tail.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          238.5,
          279.84
        ],
        "order": 0,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "tail"
      },
      {
        "id": "ear_r",
        "source": "/assets/companions/rig-v2/child/base/ear_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          129.0,
          175.93
        ],
        "order": 1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "ear"
      },
      {
        "id": "ear_l",
        "source": "/assets/companions/rig-v2/child/base/ear_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          374.0,
          161.27
        ],
        "order": 2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -1,
        "phase": 0,
        "motion": "ear"
      },
      {
        "id": "leg_r",
        "source": "/assets/companions/rig-v2/child/base/leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          224.0,
          380.69
        ],
        "order": 3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "leg_l",
        "source": "/assets/companions/rig-v2/child/base/leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          301.0,
          380.68
        ],
        "order": 4,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.325,
        "motion": "leg"
      },
      {
        "id": "body",
        "source": "/assets/companions/rig-v2/child/base/body.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          258.5,
          278.25
        ],
        "order": 5,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "body"
      },
      {
        "id": "arm_r",
        "source": "/assets/companions/rig-v2/child/base/arm_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          186.0,
          298.25
        ],
        "order": -2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.3,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "arm_l",
        "source": "/assets/companions/rig-v2/child/base/arm_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          331.0,
          295.25
        ],
        "order": -2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -0.3,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "collar_front",
        "source": "/assets/companions/rig-v2/child/base/collar_front.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          258.0,
          277.12
        ],
        "order": 10,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      },
      {
        "id": "head",
        "source": "/assets/companions/rig-v2/child/base/head.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          254.94,
          276.0
        ],
        "order": 9,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "body",
        "stateSources": {
          "sleep": "/assets/companions/rig-v2/child/base/head_sleep.png"
        }
      },
      {
        "id": "side_leaf_r",
        "source": "/assets/companions/rig-v2/child/base/side_leaf_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          177.5,
          303.73
        ],
        "order": -1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "leaf"
      },
      {
        "id": "side_leaf_l",
        "source": "/assets/companions/rig-v2/child/base/side_leaf_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          352.5,
          307.45
        ],
        "order": -1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "leaf"
      },
      {
        "id": "body_front",
        "source": "/assets/companions/rig-v2/child/base/body_front.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          258.5,
          278.25
        ],
        "order": 8,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      }
    ]
  },
  "custom": {
    "version": 1,
    "species": "custom",
    "formId": "base",
    "archetype": "upright",
    "canvas": [
      512,
      512
    ],
    "anchor": [
      256,
      448
    ],
    "safeBounds": [
      24,
      24,
      464,
      456
    ],
    "shadow": "runtime",
    "sleepExpression": "eyelids",
    "parts": [
      {
        "id": "tail",
        "source": "/assets/companions/rig-v2/custom/base/tail.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          355.5,
          373.03
        ],
        "order": 0,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "tail"
      },
      {
        "id": "ear_r",
        "source": "/assets/companions/rig-v2/custom/base/ear_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          126.5,
          191.54
        ],
        "order": 1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "ear"
      },
      {
        "id": "ear_l",
        "source": "/assets/companions/rig-v2/custom/base/ear_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          405.0,
          194.63
        ],
        "order": 2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -1,
        "phase": 0,
        "motion": "ear"
      },
      {
        "id": "leg_r",
        "source": "/assets/companions/rig-v2/custom/base/leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          215.0,
          417.22
        ],
        "order": 3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "leg_l",
        "source": "/assets/companions/rig-v2/custom/base/leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          295.5,
          365.91
        ],
        "order": 4,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.325,
        "motion": "leg"
      },
      {
        "id": "body",
        "source": "/assets/companions/rig-v2/custom/base/body.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          254.5,
          313.99
        ],
        "order": 5,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "body"
      },
      {
        "id": "arm_r",
        "source": "/assets/companions/rig-v2/custom/base/arm_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          176.5,
          350.19
        ],
        "order": -2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.3,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "arm_l",
        "source": "/assets/companions/rig-v2/custom/base/arm_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          323.0,
          343.42
        ],
        "order": -2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -0.3,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "collar_front",
        "source": "/assets/companions/rig-v2/custom/base/collar_front.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          278.0,
          326.08
        ],
        "order": -3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      },
      {
        "id": "head",
        "source": "/assets/companions/rig-v2/custom/base/head.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          277.0,
          123.94
        ],
        "order": 9,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "body",
        "stateSources": {
          "sleep": "/assets/companions/rig-v2/custom/base/head_sleep.png"
        }
      },
      {
        "id": "body_front",
        "source": "/assets/companions/rig-v2/custom/base/body_front.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          254.5,
          313.99
        ],
        "order": 8,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      }
    ]
  },
  "dog": {
    "version": 1,
    "species": "dog",
    "formId": "base",
    "archetype": "quadruped",
    "canvas": [
      512,
      512
    ],
    "anchor": [
      256,
      448
    ],
    "safeBounds": [
      24,
      24,
      464,
      456
    ],
    "shadow": "runtime",
    "sleepExpression": "eyelids",
    "parts": [
      {
        "id": "tail",
        "source": "/assets/companions/rig-v2/dog/base/tail.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          387.0,
          187.68
        ],
        "order": 0,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "tail"
      },
      {
        "id": "hind_leg_r",
        "source": "/assets/companions/rig-v2/dog/base/hind_leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          237.0,
          346.84
        ],
        "order": 1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.325,
        "motion": "leg"
      },
      {
        "id": "hind_leg_l",
        "source": "/assets/companions/rig-v2/dog/base/hind_leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          350.5,
          311.61
        ],
        "order": 2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "body",
        "source": "/assets/companions/rig-v2/dog/base/body.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          265.0,
          206.17
        ],
        "order": 3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "body"
      },
      {
        "id": "front_leg_r",
        "source": "/assets/companions/rig-v2/dog/base/front_leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          169.5,
          292.91
        ],
        "order": 4,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "front_leg_l",
        "source": "/assets/companions/rig-v2/dog/base/front_leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          233.5,
          291.09
        ],
        "order": 5,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.325,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "chest_fluff",
        "source": "/assets/companions/rig-v2/dog/base/chest_fluff.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          180.5,
          234.78
        ],
        "order": 6,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      },
      {
        "id": "head",
        "source": "/assets/companions/rig-v2/dog/base/head.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          198.5,
          73.53
        ],
        "order": 7,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "body",
        "stateSources": {
          "sleep": "/assets/companions/rig-v2/dog/base/head_sleep.png"
        }
      }
    ]
  },
  "dragon": {
    "version": 1,
    "species": "dragon",
    "formId": "base",
    "archetype": "quadruped",
    "canvas": [
      512,
      512
    ],
    "anchor": [
      256,
      448
    ],
    "safeBounds": [
      24,
      24,
      464,
      456
    ],
    "shadow": "runtime",
    "sleepExpression": "eyelids",
    "parts": [
      {
        "id": "tail",
        "source": "/assets/companions/rig-v2/dragon/base/tail.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          369.5,
          193.86
        ],
        "order": 0,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "tail"
      },
      {
        "id": "hind_leg_r",
        "source": "/assets/companions/rig-v2/dragon/base/hind_leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          196.0,
          350.37
        ],
        "order": 1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.325,
        "motion": "leg"
      },
      {
        "id": "hind_leg_l",
        "source": "/assets/companions/rig-v2/dragon/base/hind_leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          304.5,
          293.95
        ],
        "order": 2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "body",
        "source": "/assets/companions/rig-v2/dragon/base/body.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          230.0,
          265.53
        ],
        "order": 3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "body"
      },
      {
        "id": "front_leg_r",
        "source": "/assets/companions/rig-v2/dragon/base/front_leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          123.0,
          318.05
        ],
        "order": 4,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "front_leg_l",
        "source": "/assets/companions/rig-v2/dragon/base/front_leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          188.0,
          316.24
        ],
        "order": 5,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.325,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "chest_fluff",
        "source": "/assets/companions/rig-v2/dragon/base/chest_fluff.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          154.5,
          273.71
        ],
        "order": 6,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      },
      {
        "id": "head",
        "source": "/assets/companions/rig-v2/dragon/base/head.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          168.5,
          101.0
        ],
        "order": 7,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "body",
        "stateSources": {
          "sleep": "/assets/companions/rig-v2/dragon/base/head_sleep.png"
        }
      }
    ]
  },
  "duck": {
    "version": 1,
    "species": "duck",
    "formId": "base",
    "archetype": "upright",
    "canvas": [
      512,
      512
    ],
    "anchor": [
      256,
      448
    ],
    "safeBounds": [
      24,
      24,
      464,
      456
    ],
    "shadow": "runtime",
    "sleepExpression": "eyelids",
    "parts": [
      {
        "id": "tail",
        "source": "/assets/companions/rig-v2/duck/base/tail.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          349.0,
          299.22
        ],
        "order": 0,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "tail"
      },
      {
        "id": "leg_r",
        "source": "/assets/companions/rig-v2/duck/base/leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          188.5,
          383.34
        ],
        "order": 1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "leg_l",
        "source": "/assets/companions/rig-v2/duck/base/leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          327.0,
          381.64
        ],
        "order": 2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.375,
        "motion": "leg"
      },
      {
        "id": "body",
        "source": "/assets/companions/rig-v2/duck/base/body.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          260.5,
          262.37
        ],
        "order": 3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "body"
      },
      {
        "id": "wing_r",
        "source": "/assets/companions/rig-v2/duck/base/wing_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          163.5,
          252.52
        ],
        "order": 4,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.3,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "wing_l",
        "source": "/assets/companions/rig-v2/duck/base/wing_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          356.0,
          247.45
        ],
        "order": 5,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -0.3,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "chest_fluff",
        "source": "/assets/companions/rig-v2/duck/base/chest_fluff.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          259.0,
          272.58
        ],
        "order": 6,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      },
      {
        "id": "head",
        "source": "/assets/companions/rig-v2/duck/base/head.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          260.5,
          65.46
        ],
        "order": 7,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "body",
        "stateSources": {
          "sleep": "/assets/companions/rig-v2/duck/base/head_sleep.png"
        }
      }
    ]
  },
  "fox": {
    "version": 1,
    "species": "fox",
    "formId": "base",
    "archetype": "quadruped",
    "canvas": [
      512,
      512
    ],
    "anchor": [
      256,
      448
    ],
    "safeBounds": [
      24,
      24,
      464,
      456
    ],
    "shadow": "runtime",
    "sleepExpression": "eyelids",
    "parts": [
      {
        "id": "tail",
        "source": "/assets/companions/rig-v2/fox/base/tail.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          286,
          373
        ],
        "order": 0,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.15,
        "motion": "tail"
      },
      {
        "id": "hind_leg_r",
        "source": "/assets/companions/rig-v2/fox/base/hind_leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          245,
          326
        ],
        "order": 1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.325,
        "motion": "leg"
      },
      {
        "id": "hind_leg_l",
        "source": "/assets/companions/rig-v2/fox/base/hind_leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          283,
          326
        ],
        "order": 2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "body",
        "source": "/assets/companions/rig-v2/fox/base/body.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          215,
          345
        ],
        "order": 3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "body"
      },
      {
        "id": "front_leg_r",
        "source": "/assets/companions/rig-v2/fox/base/front_leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          141,
          330
        ],
        "order": 4,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "front_leg_l",
        "source": "/assets/companions/rig-v2/fox/base/front_leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          197,
          330
        ],
        "order": 5,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.325,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "chest_fluff",
        "source": "/assets/companions/rig-v2/fox/base/chest_fluff.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          156,
          280
        ],
        "order": 7,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      },
      {
        "id": "head",
        "source": "/assets/companions/rig-v2/fox/base/head.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          183,
          264
        ],
        "order": 6,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "body",
        "stateSources": {
          "sleep": "/assets/companions/rig-v2/fox/base/head_sleep.png"
        }
      }
    ]
  },
  "frog": {
    "version": 1,
    "species": "frog",
    "formId": "base",
    "archetype": "frog",
    "canvas": [
      512,
      512
    ],
    "anchor": [
      256,
      448
    ],
    "safeBounds": [
      24,
      24,
      464,
      456
    ],
    "shadow": "runtime",
    "sleepExpression": "eyelids",
    "parts": [
      {
        "id": "thigh_r",
        "source": "/assets/companions/rig-v2/frog/base/thigh_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          115.42,
          279.28
        ],
        "order": 0,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.8,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "foot_r",
        "source": "/assets/companions/rig-v2/frog/base/foot_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          115.7,
          399.13
        ],
        "order": 1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -0.5,
        "phase": 0,
        "parent": "thigh_r",
        "motion": "leg"
      },
      {
        "id": "thigh_l",
        "source": "/assets/companions/rig-v2/frog/base/thigh_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          383.0,
          272.69
        ],
        "order": 2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -0.8,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "foot_l",
        "source": "/assets/companions/rig-v2/frog/base/foot_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          398.3,
          399.13
        ],
        "order": 3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.5,
        "phase": 0,
        "parent": "thigh_l",
        "motion": "leg"
      },
      {
        "id": "body",
        "source": "/assets/companions/rig-v2/frog/base/body.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          268.0,
          350.19
        ],
        "order": 4,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "body"
      },
      {
        "id": "arm_r",
        "source": "/assets/companions/rig-v2/frog/base/arm_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          140.45,
          266.55
        ],
        "order": 5,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.25,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "arm_l",
        "source": "/assets/companions/rig-v2/frog/base/arm_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          372.44,
          266.55
        ],
        "order": 6,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -0.25,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "head",
        "source": "/assets/companions/rig-v2/frog/base/head.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          260.5,
          269.14
        ],
        "order": 7,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "body",
        "stateSources": {
          "sleep": "/assets/companions/rig-v2/frog/base/head_sleep.png"
        }
      }
    ]
  },
  "robot": {
    "version": 1,
    "species": "robot",
    "formId": "base",
    "archetype": "upright",
    "canvas": [
      512,
      512
    ],
    "anchor": [
      256,
      448
    ],
    "safeBounds": [
      24,
      24,
      464,
      456
    ],
    "shadow": "runtime",
    "sleepExpression": "eyelids",
    "parts": [
      {
        "id": "leg_r",
        "source": "/assets/companions/rig-v2/robot/base/leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          208.58,
          343.45
        ],
        "order": 0,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.5,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "leg_l",
        "source": "/assets/companions/rig-v2/robot/base/leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          296.57,
          337.74
        ],
        "order": 1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.5,
        "phase": -0.45,
        "motion": "leg"
      },
      {
        "id": "arm_r",
        "source": "/assets/companions/rig-v2/robot/base/arm_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          201.33,
          290.0
        ],
        "order": 2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.3,
        "phase": -0.45,
        "motion": "leg"
      },
      {
        "id": "arm_l",
        "source": "/assets/companions/rig-v2/robot/base/arm_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          318.51,
          288.6
        ],
        "order": 3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.3,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "body",
        "source": "/assets/companions/rig-v2/robot/base/body.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          255.49,
          321.47
        ],
        "order": 4,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "body"
      },
      {
        "id": "neck",
        "source": "/assets/companions/rig-v2/robot/base/neck.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          231.55,
          271.0
        ],
        "order": 5,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      },
      {
        "id": "antenna",
        "source": "/assets/companions/rig-v2/robot/base/antenna.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          259.0,
          132.87
        ],
        "order": 6,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.3,
        "phase": 0,
        "parent": "body",
        "motion": "antenna"
      },
      {
        "id": "head",
        "source": "/assets/companions/rig-v2/robot/base/head.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          257.5,
          258.65
        ],
        "order": 7,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "body",
        "stateSources": {
          "sleep": "/assets/companions/rig-v2/robot/base/head_sleep.png"
        }
      }
    ]
  },
  "spirit": {
    "version": 1,
    "species": "spirit",
    "formId": "base",
    "archetype": "upright",
    "canvas": [
      512,
      512
    ],
    "anchor": [
      256,
      448
    ],
    "safeBounds": [
      24,
      24,
      464,
      456
    ],
    "shadow": "runtime",
    "sleepExpression": "eyelids",
    "parts": [
      {
        "id": "tail",
        "source": "/assets/companions/rig-v2/spirit/base/tail.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          341.0,
          352.42
        ],
        "order": 0,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "tail"
      },
      {
        "id": "ear_r",
        "source": "/assets/companions/rig-v2/spirit/base/ear_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          124.0,
          152.16
        ],
        "order": 1,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "ear"
      },
      {
        "id": "ear_l",
        "source": "/assets/companions/rig-v2/spirit/base/ear_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          382.0,
          150.7
        ],
        "order": 2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -1,
        "phase": 0,
        "motion": "ear"
      },
      {
        "id": "leg_r",
        "source": "/assets/companions/rig-v2/spirit/base/leg_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          198.5,
          388.98
        ],
        "order": 3,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "leg"
      },
      {
        "id": "leg_l",
        "source": "/assets/companions/rig-v2/spirit/base/leg_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          299.5,
          332.6
        ],
        "order": 4,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": -0.325,
        "motion": "leg"
      },
      {
        "id": "body",
        "source": "/assets/companions/rig-v2/spirit/base/body.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          250.0,
          273.89
        ],
        "order": 5,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "motion": "body"
      },
      {
        "id": "arm_r",
        "source": "/assets/companions/rig-v2/spirit/base/arm_r.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          174.0,
          295.18
        ],
        "order": -2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 0.3,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "arm_l",
        "source": "/assets/companions/rig-v2/spirit/base/arm_l.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          324.0,
          294.98
        ],
        "order": -2,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": -0.3,
        "phase": 0,
        "parent": "body",
        "motion": "leg"
      },
      {
        "id": "collar_front",
        "source": "/assets/companions/rig-v2/spirit/base/collar_front.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          253.0,
          262.53
        ],
        "order": 8,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      },
      {
        "id": "head",
        "source": "/assets/companions/rig-v2/spirit/base/head.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          261.5,
          130.37
        ],
        "order": 9,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body",
        "motion": "body",
        "stateSources": {
          "sleep": "/assets/companions/rig-v2/spirit/base/head_sleep.png"
        }
      },
      {
        "id": "sprout",
        "source": "/assets/companions/rig-v2/spirit/base/sprout.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          274.5,
          75.33
        ],
        "order": 10,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "head",
        "motion": "leaf"
      },
      {
        "id": "body_front",
        "source": "/assets/companions/rig-v2/spirit/base/body_front.png",
        "bounds": [
          0,
          0,
          512,
          512
        ],
        "pivot": [
          250.0,
          273.89
        ],
        "order": 8,
        "rest": {
          "translate": [
            0,
            0
          ],
          "rotate": 0,
          "scale": [
            1,
            1
          ]
        },
        "multiplier": 1,
        "phase": 0,
        "parent": "body"
      }
    ]
  }
};
