import 'dotenv/config';
import express from 'express';
import { createServer } from 'node:http';
import cors from 'cors';
import { Server } from 'socket.io';
import { connectDb } from './config/db.js';
import itemRoutes from './routes/items.js';
import mediaRoutes from './routes/media.js';
import linkPreviewRoutes from './routes/linkPreview.js';
import desktopSettingsRoutes from './routes/desktopSettings.js';
import desktopWindowRoutes from './routes/desktopWindows.js';
import desktopStrokeRoutes from './routes/desktopStrokes.js';
import { setupRealtime } from './realtime.js';
import { errorHandler, notFound } from './middleware/error.js';

const app = express();
const origin = process.env.CLIENT_ORIGIN || 'http://localhost:5173';
const httpServer = createServer(app);
const io = new Server(httpServer, { cors: { origin, methods: ['GET', 'POST'] }, pingInterval: 25000, pingTimeout: 20000 });
app.use(cors({ origin }));
app.use(express.json({ limit: '1mb' }));
app.get('/api/health', (req, res) => res.json({ ok: true }));
app.use('/api/items', itemRoutes);
app.use('/api/media', mediaRoutes);
app.use('/api/link-preview', linkPreviewRoutes);
app.use('/api/settings/desktop', desktopSettingsRoutes);
app.use('/api/desktop/windows', desktopWindowRoutes);
app.use('/api/desktop/strokes', desktopStrokeRoutes);
app.use(notFound);
app.use(errorHandler);

setupRealtime(io);
connectDb().then(() => httpServer.listen(process.env.PORT || 5000, () => console.info(`API listening on ${process.env.PORT || 5000}`))).catch((error) => { console.error(error); process.exit(1); });
