import type * as React from 'react';
import * as SelectPrimitive from '@radix-ui/react-select';
import { Check, ChevronDown, ChevronUp } from 'lucide-react';
import { cn } from '@/lib/utils';

export const Select = SelectPrimitive.Root;
export const SelectGroup = SelectPrimitive.Group;
export const SelectValue = SelectPrimitive.Value;
export const SelectTrigger = ({ className, children, ...props }: React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger>) => <SelectPrimitive.Trigger className={cn('flex h-10 w-full items-center justify-between rounded-xl border border-white/15 bg-black/15 px-3 text-sm text-ink outline-none focus:ring-2 focus:ring-royal/30', className)} {...props}>{children}<SelectPrimitive.Icon><ChevronDown className='size-4 opacity-60' /></SelectPrimitive.Icon></SelectPrimitive.Trigger>;
export const SelectContent = ({ className, children, position = 'popper', ...props }: React.ComponentPropsWithoutRef<typeof SelectPrimitive.Content>) => <SelectPrimitive.Portal><SelectPrimitive.Content position={position} className={cn('z-[1100] min-w-32 overflow-hidden rounded-xl border border-white/15 bg-[#0b173d]/95 text-ink shadow-2xl backdrop-blur-xl', className)} {...props}><SelectPrimitive.ScrollUpButton className='flex items-center justify-center py-1'><ChevronUp className='size-4' /></SelectPrimitive.ScrollUpButton><SelectPrimitive.Viewport className='p-1'>{children}</SelectPrimitive.Viewport><SelectPrimitive.ScrollDownButton className='flex items-center justify-center py-1'><ChevronDown className='size-4' /></SelectPrimitive.ScrollDownButton></SelectPrimitive.Content></SelectPrimitive.Portal>;
export const SelectItem = ({ className, children, ...props }: React.ComponentPropsWithoutRef<typeof SelectPrimitive.Item>) => <SelectPrimitive.Item className={cn('relative flex cursor-default select-none items-center rounded-lg py-1.5 pl-8 pr-2 text-sm outline-none focus:bg-white/10 data-[disabled]:pointer-events-none data-[disabled]:opacity-50', className)} {...props}><span className='absolute left-2 flex size-4 items-center justify-center'><SelectPrimitive.ItemIndicator><Check className='size-4' /></SelectPrimitive.ItemIndicator></span><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText></SelectPrimitive.Item>;
